"""Read/write/validate an OKF v0.2 bundle (markdown + YAML frontmatter).

Spec: https://github.com/GoogleCloudPlatform/knowledge-catalog/blob/main/okf/SPEC.md
Conformance rules honored here:
  - every non-reserved .md file has parseable YAML frontmatter with non-empty `type`
  - index.md carries only `okf_version` frontmatter and a sectioned listing
  - log.md is a flat, date-grouped changelog, newest first
Notifications are an opt-in vocabulary addition (the spec adds vocabulary, not rules):
a concept may carry `notifications: [{id, at, title, body}]`.
"""

import datetime as dt
import re
import unicodedata
import uuid
from pathlib import Path
from zoneinfo import ZoneInfo

import frontmatter
import yaml

RESERVED = {"index.md", "log.md", "README.md"}


class OkfError(ValueError):
    pass


def _slugify(text: str) -> str:
    text = unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode()
    text = re.sub(r"[^a-zA-Z0-9]+", "-", text).strip("-").lower()
    return text[:60] or "memory"


class Bundle:
    def __init__(self, root: Path, timezone: str = "America/New_York"):
        self.root = Path(root)
        self.tz = ZoneInfo(timezone)
        (self.root / "memories").mkdir(parents=True, exist_ok=True)
        (self.root / "references").mkdir(parents=True, exist_ok=True)

    # ---------- reading ----------

    def concept_paths(self) -> list[Path]:
        return sorted(
            p
            for p in self.root.rglob("*.md")
            if p.name not in RESERVED and "references" not in p.parts and ".git" not in p.parts
        )

    def load_concept(self, rel_path: str) -> dict:
        path = (self.root / rel_path).resolve()
        if not path.is_relative_to(self.root.resolve()) or path.name in RESERVED:
            raise OkfError(f"not a concept path: {rel_path}")
        post = frontmatter.load(path)
        meta = dict(post.metadata)
        if not str(meta.get("type", "")).strip():
            raise OkfError(f"{rel_path}: missing required `type`")
        return {"path": str(path.relative_to(self.root)), "frontmatter": meta, "body": post.content}

    def list_concepts(self) -> list[dict]:
        out = []
        for p in self.concept_paths():
            try:
                out.append(self.load_concept(str(p.relative_to(self.root))))
            except (OkfError, yaml.YAMLError):
                continue  # spec: consumers tolerate malformed neighbors
        out.sort(key=lambda c: str(c["frontmatter"].get("generated", {}).get("at", "")), reverse=True)
        return out

    # ---------- writing ----------

    def write_concept(self, meta: dict, body: str, slug: str | None = None) -> str:
        if not str(meta.get("type", "")).strip():
            raise OkfError("concept requires non-empty `type`")
        for n in meta.get("notifications") or []:
            if not all(n.get(k) for k in ("at", "title", "body")):
                raise OkfError("notification entries require at, title, body")
            n.setdefault("id", str(uuid.uuid4()))
        slug = _slugify(slug or meta.get("title", "memory"))
        date = dt.datetime.now(self.tz).strftime("%Y-%m-%d")
        rel = f"memories/{date}-{slug}.md"
        i = 2
        while (self.root / rel).exists():
            rel = f"memories/{date}-{slug}-{i}.md"
            i += 1
        fm = yaml.safe_dump(meta, sort_keys=False, allow_unicode=True, default_flow_style=False)
        (self.root / rel).write_text(f"---\n{fm}---\n\n{body.strip()}\n", encoding="utf-8")
        return rel

    def save_reference(self, kind: str, filename: str, data: bytes) -> str:
        stamp = dt.datetime.now(self.tz).strftime("%Y-%m-%d-%H%M%S")
        safe = _slugify(Path(filename).stem) + Path(filename).suffix.lower()
        rel = f"references/{kind}/{stamp}-{safe}"
        path = self.root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
        return rel

    def regenerate_index(self) -> None:
        """Deterministically rebuild index.md's listing, grouped by concept type."""
        by_type: dict[str, list[dict]] = {}
        for c in self.list_concepts():
            by_type.setdefault(str(c["frontmatter"]["type"]), []).append(c)
        lines = [
            "---", 'okf_version: "0.2"', "---", "",
            "# Ben's Memories", "",
            "An OKF v0.2 bundle of personal memories, generated by the Recall app.", "",
        ]
        for t in sorted(by_type):
            lines.append(f"## {t.title()}")
            lines.append("")
            for c in by_type[t]:
                desc = c["frontmatter"].get("description", "")
                title = c["frontmatter"].get("title", c["path"])
                lines.append(f"- [{title}](/{c['path']})" + (f" — {desc}" if desc else ""))
            lines.append("")
        lines += ["## References", "",
                  "- [references/](references/) — original audio recordings and photos that memories derive from.", ""]
        (self.root / "index.md").write_text("\n".join(lines), encoding="utf-8")

    def append_log(self, entry: str) -> None:
        today = dt.datetime.now(self.tz).strftime("%Y-%m-%d")
        path = self.root / "log.md"
        text = path.read_text(encoding="utf-8") if path.exists() else "# Log\n"
        heading = f"## {today}"
        if heading in text:
            text = text.replace(heading, f"{heading}\n\n- {entry}", 1)
            text = re.sub(r"\n{3,}", "\n\n", text)
        else:
            # newest first: insert right after the "# Log" title
            text = re.sub(r"^# Log\n", f"# Log\n\n{heading}\n\n- {entry}\n", text, count=1)
        path.write_text(text, encoding="utf-8")

    # ---------- notifications ----------

    def notifications(self) -> list[dict]:
        out = []
        for c in self.list_concepts():
            for n in c["frontmatter"].get("notifications") or []:
                out.append({
                    "id": str(n.get("id", "")),
                    "at": str(n.get("at", "")),
                    "title": str(n.get("title", "")),
                    "body": str(n.get("body", "")),
                    "memory_path": c["path"],
                })
        out.sort(key=lambda n: n["at"])
        return out

    # ---------- conformance ----------

    def validate(self) -> list[str]:
        problems = []
        for p in self.concept_paths():
            rel = str(p.relative_to(self.root))
            try:
                frontmatter_meta = frontmatter.load(p).metadata
                if not str(frontmatter_meta.get("type", "")).strip():
                    problems.append(f"{rel}: missing required `type`")
            except yaml.YAMLError as e:
                problems.append(f"{rel}: unparseable frontmatter ({e})")
        return problems
