#!/bin/zsh
# Generate the Xcode project, build Recall, and install it on the paired iPhone.
set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
IOS="$REPO/ios/Recall"
XCODEGEN="$REPO/tools/xcodegen/bin/xcodegen"
SERVER_URL="${SERVER_URL:-https://bens-mac-mini.tailab3f3c.ts.net:8443}"
DEVICE_NAME="${DEVICE_NAME:-iPhone}"

# Bake the server URL + API token into a gitignored source file.
API_TOKEN=$(grep '^API_TOKEN=' "$REPO/server/.env" | cut -d= -f2-)
[ -n "$API_TOKEN" ] || { echo "API_TOKEN missing from server/.env" >&2; exit 1; }
cat > "$IOS/Sources/Secrets.swift" <<EOF
// Generated by scripts/deploy-ios.sh — do not commit.
import Foundation

enum Secrets {
    static let serverURL = URL(string: "$SERVER_URL")!
    static let apiToken = "$API_TOKEN"
}
EOF

cd "$IOS"
"$XCODEGEN" generate

DERIVED="$REPO/ios/build"
xcodebuild -project Recall.xcodeproj -scheme Recall \
    -destination 'generic/platform=iOS' \
    -derivedDataPath "$DERIVED" \
    -allowProvisioningUpdates build | tail -5

APP="$DERIVED/Build/Products/Debug-iphoneos/Recall.app"
DEVICE_ID=$(xcrun devicectl list devices 2>/dev/null | grep -i "$DEVICE_NAME" | grep -Eo '[0-9A-F-]{36}' | head -1)
[ -n "$DEVICE_ID" ] || { echo "No paired device matching '$DEVICE_NAME'" >&2; exit 1; }
xcrun devicectl device install app --device "$DEVICE_ID" "$APP"
echo "Installed Recall on device $DEVICE_ID"
